# Generated by Django 3.1.2 on 2021-06-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hypokinesia', models.IntegerField()),
                ('Obesity', models.IntegerField()),
                ('Active_Exercise', models.IntegerField()),
                ('Go_Up_Stair', models.IntegerField()),
                ('Up_Chair', models.IntegerField()),
                ('Walk_15', models.IntegerField()),
                ('With_Out_Cane', models.IntegerField()),
                ('Going_Out', models.IntegerField()),
                ('High_blood_pressure', models.IntegerField()),
                ('Osteoporosis', models.IntegerField()),
                ('Fall', models.IntegerField()),
                ('Ex_gui', models.IntegerField()),
            ],
            options={
                'db_table': 'Health',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('group0', models.BooleanField()),
                ('group1', models.BooleanField()),
                ('group2', models.BooleanField()),
                ('group3', models.BooleanField()),
                ('group4', models.BooleanField()),
                ('group5', models.BooleanField()),
                ('guide', models.IntegerField()),
            ],
            options={
                'db_table': 'sport',
                'managed': False,
            },
        ),
    ]
